### PR TITLE
Boot docs

### PR DESCRIPTION
**Pull request by ajeddeloh**
Very much a WIP, wanted to throw these up before I went on vacation

### CODE REVIEW

**Comment by ashcrow** [comment]
Is this still planned to be done?

**Comment by ajeddeloh** [comment]
I'm not going to get to this before I leave, it's vrey out of date now anyway.

**Comment by dustymabe** [comment]
looks like some good stuff in there. would be nice if somebody picked it up

**Comment by jlebon** [comment]
Yeah, agreed. Filed https://github.com/coreos/fedora-coreos-docs/issues/24 so we don't forget about it.

**Pull request closed without merging**
