### PR TITLE
storage: add part number to butane example

### PR DESCRIPTION
**Pull request by prestist**
Fixes: [COS-1706](https://issues.redhat.com/browse/COS-1706)

### CODE REVIEW

**Comment by travier** [comment]
https://docs.openshift.com/container-platform/4.15/installing/installing_bare_metal/installing-bare-metal-network-customizations.html#installation-user-infra-machines-advanced_vardisk_installing-bare-metal-network-customizations does not mention the number unless I'm missing something

**Comment by prestist** [comment]
@travier Yeah it does not mention it either, and needs to be updated. https://github.com/openshift/openshift-docs/pull/74419

**Comment by prestist** [comment]
1 through 4 are reserved for specific purposes, and so var would be 5.

Ugh Just noticed butane is wrong too.

Filesystems and partitions https://coreos.github.io/butane/examples/

**Comment by travier** [comment]
Isn't the partition number automatically picked-up by Ignition?

From https://coreos.github.io/ignition/configuration-v3_4/:
> number (integer): the partition number, which dictates its position in the partition table (one-indexed). If zero, use the next available partition slot.

**Comment by prestist** [comment]
> Isn't the partition number automatically picked-up by Ignition?
> 
> From https://coreos.github.io/ignition/configuration-v3_4/:
> 
> > number (integer): the partition number, which dictates its position in the partition table (one-indexed). If zero, use the next available partition slot.

Yeah, the thought was to include the number like the root part above. While its not necessary, it gives some context, and consistency

**Comment by jlebon** [comment]
The difference with the root one is that it's modifying an existing partition (so it needs to refer to it), whereas the /var one is new. And actually, ideally that root stanza wouldn't be necessary at all. The problem is without it, the next partition will trap it and prevent the rootfs from getting enough space.

Adding the partition number for /var seems OK though it's also totally fine to omit it, so ideally we do have examples that showcase that too.

**Comment by prestist** [comment]
Ok, I went and added an example with a number and notes. I hope this is fine lmk.

**Comment by jlebon** [comment]
I'm not sure I understand. Can you clarify: did a user hit a bug somehow related to this? How did this come on your radar?

**Comment by prestist** [comment]
@jlebon, it was something I stumbled across with an old co-worker, and we made a ticket for it. Im not sure I captured enough details at the time. I am willing to close this if you think its not worth it. No need to spin wheels on something that negatively impacts the project.

**Pull request closed without merging**
