### PR TITLE
sysconfig-network-configuration: fix hyperlink

### PR DESCRIPTION
**Pull request by dustymabe**
Not sure why this link is broken. Maybe a recent rework of my blog made the links change. Either way, this is the new link.

### CODE REVIEW

**Comment by dustymabe** [comment]
weird.. rendering this on the website seems to generate a link with some extra stuff in it: `https://dustymabe.com/2020/11/18/coreos-install-via-live-iso%E2%80%94%E2%80%8Bcopy-network/`

**Comment by travier** [comment]
You web server is weirdly configured.

- `https://dustymabe.com/2020/11/18/coreos-install-via-live-iso--copy-network` (no end slash) redirects me to `https://dustymabe.com:8443/2020/11/18/coreos-install-via-live-iso--copy-network/` which we can't access.
- `https://dustymabe.com/2020/11/18/coreos-install-via-live-iso--copy-network/` works.

**Comment by travier** [comment]
This is likely a `--` to long `-` substitution done by adoc. Not sure how to disable that.

**Comment by travier** [comment]
Maybe: https://docs.asciidoctor.org/asciidoc/latest/macros/links/#encode-reserved-characters ?

**Review by travier — APPROVED** [review]

**Pull request merged**
