### PR TITLE
sysconfig: netconfig: Remove the workarounds for NM bugs

### PR DESCRIPTION
**Pull request by dustymabe**
The NM bugs we were working around [1], [2] are fixed upstream
now so let's remove the workarounds from the code.

[1] https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/issues/509
[2] https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/issues/581

### CODE REVIEW

**Comment by dustymabe** [comment]
pending new NM rpm in Fedora.

**Comment by travier** [comment]
Are we waiting for F34 here or is this ready now?

**Comment by dustymabe** [comment]
This is ready. Rebased on top of latest.

**Review by travier — APPROVED** [review]
Not tested but LGTM

**Pull request merged**
