### PR TITLE
pages/platforms: Add ibmcloud to platform list

### PR DESCRIPTION
**Pull request by ashcrow**
See: https://github.com/coreos/fedora-coreos-tracker/issues/277

### CODE REVIEW

**Comment by ajeddeloh** [comment]
LGTM though maybe we want to add something to these showing how supported it currently is? Like aliyun is in development, not ready for end users.

**Comment by ashcrow** [comment]
@ajeddeloh I think that would be a good addition. I'm keen to add a new column in a follow up PR.

**Comment by lucab** [comment]
My preference would be to keep this page as a plain reference list, and detail any caveats/unsupported bits on each relevant "Booting on XYZ" pages (which we should start writing soon-ish).

**Comment by ashcrow** [comment]
This PR is ready to merge if it is :+1:

**Comment by ashcrow** [comment]
bump :slightly_smiling_face:

**Comment by lucab** [comment]
I took my own dive into `ibmcloud` (notes [here](https://github.com/coreos/fedora-coreos-tracker/issues/277#issuecomment-545916088)).
I do fear we have to take additional details into here as the platform is really a 3-in-1 beast with different semantics and it's not clear to me which part of that we are targeting.

**Comment by ashcrow** [comment]
@lucab I'll verify which sub environment it is today

**Pull request merged**
