### PR TITLE
sysconfig: add instructions for configuring SwapOnZRAM

### PR DESCRIPTION
**Pull request by dustymabe**
Related to https://github.com/coreos/fedora-coreos-tracker/issues/509

### CODE REVIEW

**Review by travier — APPROVED** [review]
LGTM

**Comment by travier** [comment]
Hold for Fedora 33?

**Comment by dustymabe** [comment]
> Hold for Fedora 33?

it landed in `testing-devel` so we should be good to merge this after the round of releases this week.

**Comment by dustymabe** [comment]
Should be in the latest `testing`.

**Pull request merged**
