### PR TITLE
create separate page for aws provisioning

### PR DESCRIPTION
**Pull request by sumantro93**
@dustymabe can you have a look at this?

### CODE REVIEW

**Comment by lucab** [comment]
Thanks for the PR!
Please do note that we have an ongoing discussion open in parallel on this specific part of the docs structure: https://github.com/coreos/fedora-coreos-docs/pull/63

**Comment by sumantro93** [comment]
@lucab thanks for the pointing me to the #63 
I will be happy to help

**Comment by lucab** [comment]
@sumantro93 if you have cycles and want to explore the re-structuring suggested in https://github.com/coreos/fedora-coreos-docs/pull/63#issuecomment-614509060 and see if it works, that would be helpful. If it does, we can land it in this PR here.

**Comment by lucab** [comment]
Fixed via https://github.com/coreos/fedora-coreos-docs/pull/81.

**Pull request closed without merging**
