### PR TITLE
Tutorials initialized

### PR DESCRIPTION
**Pull request by nasirhm**
Migrated these docs from @dustymabe 's Blog post from Devconf Lab.

We're planning to use it in our Hack session at Nest 
cc: @travier

### CODE REVIEW

**Comment by lucab** [comment]
@nasirhm thanks! I think you have two spurious commits in this branch (the ones touching FAQ page), can you maybe drop those?

**Comment by nasirhm** [comment]
> @nasirhm thanks! I think you have two spurious commits in this branch (the ones touching FAQ page), can you maybe drop those?

@lucab I didn't sync my local git repo with the upstream one which has caused it. I've created the second commit https://github.com/coreos/fedora-coreos-docs/pull/133/commits/44b735ff48558ccab65d09ebff5a264af30d5d3f to resolve any conflicts and keep the same FAQ page as it currently is.

**Comment by nasirhm** [comment]
I'm closing this one as my git history is pretty messed up by now. Creating a new PR to resolve any modifications in untouched files for the scope of the PR,

**Comment by nasirhm** [comment]
Here's the new PR: https://github.com/coreos/fedora-coreos-docs/pull/134

**Pull request closed without merging**
