### PR TITLE
kernel-args: Update and extend examples

### PR DESCRIPTION
**Pull request by travier**
Part 1 of https://github.com/coreos/fedora-coreos-docs/pull/269

### CODE REVIEW

**Comment by dustymabe** [comment]
oops, didn't see this first. dropped a few suggestions over in #269

**Comment by travier** [comment]
Updated with comments from #269.

**Comment by travier** [comment]
This one should be safe to merge now and #269 does the cgroups v2 switch.

**Comment by jlebon** [comment]
Ahh sorry, I made the same mistake as Dusty and reviewed https://github.com/coreos/fedora-coreos-docs/pull/269 first!

**Comment by travier** [comment]
Closing as I merged all content into a single PR to simplify.

**Pull request closed without merging**
