### PR TITLE
Split AWS/qemu instructions out of getting-started to their own pages

### PR DESCRIPTION
**Pull request by bgilbert**
Prompted by the discussion in #62.

### CODE REVIEW

**Comment by lucab** [comment]
I don't have strong opinions here. This is definitely more consistent, but now getting-started lacks any immediate actionable snippet. I was thinking of keeping the "aws with cloud keys" and "qemu with temporary storage" snippets and then linking to further pages, but I'm also ok with this version. Either directions, PR content looks good.

I'll leave some space for @jlebon who initially wrote this.

**Comment by dustymabe** [comment]
> I don't have strong opinions here. This is definitely more consistent, but now getting-started lacks any immediate actionable snippet. I was thinking of keeping the "aws with cloud keys" and "qemu with temporary storage" snippets and then linking to further pages, but I'm also ok with this version. Either directions, PR content looks good.

I wonder if asciidoc has the ability to source content from other places. i.e. we would be able to include the content in both places but not duplicate the text, with is a maintainability problem.

**Comment by lucab** [comment]
@dustymabe it can do that: https://github.com/coreos/fedora-coreos-docs/blame/master/modules/ROOT/pages/auto-updates.adoc#L63

**Comment by jlebon** [comment]
Lukewarm on this myself. I agree with Luca it's a bit anticlimactic for a "Getting Started" page to only link to more links containing instructions. But maybe it's OK... Sharing content for the basic scenarios as described above sounds like an interesting compromise.

**Comment by lucab** [comment]
Middleground proposal for this:
 * split the current getting-started steps out of there, into four dedicated files:
   1. getting-started-aws
   2. getting-started-qemu
   3. provisioning-aws
   4. provisioning-qemu
 * setup includes so that the getting-started-* sections are sourced by both the getting-started page and by their relevant provisioning-* one

I think @bgilbert prefers keeping only the getting-started-qemu steps as an introduction, I'm fine either ways (anecdotally I think this may drag people into qemu networking woes, though).

**Comment by lucab** [comment]
Closing, https://github.com/coreos/fedora-coreos-docs/pull/97 took care of this.

**Pull request closed without merging**
