### PR TITLE
update-streams: fix rebase command

### PR DESCRIPTION
**Pull request by dustymabe**
Now requires `--bypass-driver` to work.

### CODE REVIEW

**Review by jlebon — APPROVED** [review]

**Comment by lucab** [comment]
Uhm, but the step right before that is stopping `zincati.service`, so there shouldn't be an update-driver active anymore at that point.
Did you skip a step, or do we have a bug around here maybe?

/cc @kelvinfan001

**Comment by kelvinfan001** [comment]
ah, I think we found a bug here. `rpm-ostree` doesn't have an API to de-register as driver right now. I think this means we need to implement that and then get Zincati to de-register before it becomes inactive.

**Comment by dustymabe** [comment]
> Uhm, but the step right before that is stopping `zincati.service`, so there shouldn't be an update-driver active anymore at that point.
> Did you skip a step, or do we have a bug around here maybe?

Nope. I did stop Zincati 🙂.

**Comment by dustymabe** [comment]
Thanks for opening the bug @kelvinfan001

**Pull request merged**
